module.exports = Object.freeze({
  PENDING_VERIFICATION: "PENDING_VERIFICATION",
  PENDING_PAYMENT: "PENDING_PAYMENT",
  CONFIRMED: "CONFIRMED",
  PAYMENT_REJECTED: "PAYMENT_REJECTED",
  CANCELLED: "CANCELLED",
  COMPLETED: "COMPLETED",
});
